### PR TITLE
Fix #85 #86 Remove support for Emacs 24

### LINKED ISSUE #85: Review and refactor old code
Review the existing code, find bits of bad implementation and improve them.
<s>For example, `(purpose-flatten (mapcar #'window-list frames))` is bad and should be replaced by `(window-list-1 nil nil frames)`.</s> (edit: `window-list-1` doesn't work like this)

### PR DESCRIPTION
**Pull request by wyuenho**
* autoload `purpose-conf'
* remove purpose-conf instance names
* remove `subr-x' shims
* remove `purpose-alist-get'
* remove old style advice shims
* bump emacs version package requirement

## TODO:
* [x] fix tests for emacs 26.1

### CODE REVIEW

**Comment by wyuenho** [comment]
This PR should be good to go. It's a bit large but most of it is just removing old code for emacs < 25

**Comment by bmag** [comment]
Hey thanks, that's some awesome work. I've reviewed the changes, most of them are good, but I still have a few notes:

I want to remove support for Emacs 24.3 only, but keep support for versions 24.4 and 24.5, which means:
- we can't remove `purpose-alist-get`
- Package-Requires needs Emacs 24.4 and let-alist
- we need to keep the bits for `css-mode`

As for the tests, I see you basically rewrote .travis.yml, and it seems copied from Flycheck. Can you explain what was bad with the previous yml that we can't just add version 25.1, 25.3 and 26.1 to it? (25.2 and 25.3 are the same as far as Purpose is concerned)

I also see that you added `test/user-input.txt` by mistake, but I can ignore that part when merging.

I'm going to merge the non-yml parts, then apply the changes I wrote, unless you have objections to that.

**Comment by wyuenho** [comment]
Ah I misunderstood your ticket it seems. Ubuntu 16.04's Emacs only goes as high up as 24.5, so supporting it makes sense.

I just removed test/user-input.txt, I think you should probably gitignore it to avoid adding it by mistake.

It's been so long I've forgotten why I updated .travis.yml, but I'm pretty sure just adding newer versions to the matrix wouldn't work.

I'm fine with merging this. Thanks for reviewing!

**Comment by bmag** [comment]
Thank you, I cherry-picked, squashed and merged the parts of this in https://github.com/bmag/emacs-purpose/commit/5d768aa0500e5f646089b9a3c4f5e4b661112f4c and https://github.com/bmag/emacs-purpose/commit/2b20dbbc4edfdbf0811de19236c760cdb09d75ae, and applied fixes in https://github.com/bmag/emacs-purpose/commit/bcf0e644eeb0f133ad84b77e1ce14172b9b8330c and https://github.com/bmag/emacs-purpose/commit/2c0e31d43df369506b4a18d80e46fcddc5fbe4d0. 

It turns out that EIEIO classes still need the mandatory name argument in Emacs 24.5, so I had to revert the related changes. Adding tests for 25.1, 25.3 and 26.1 only required adding them to the test matrix, so any issues with EVM that existed two months ago seem to have been resolved. Other than that, the fixes I applied are more-or-less what I wrote in previous comments.

Your contribution is much appreciated.

**Pull request closed without merging**
